# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.14

# Mod Properties
mod_version=0.2
maven_group=com.cubecode
archives_base_name=cubecode
java_version=17

# Dependencies
fabric_version=0.92.6+1.20.1
rhino_version=2001.2.3-build.10
imgui_version=1.86.11